name: House price estimator CICD pipeline

env:
  SERVICE_NAME: house price estimator
  PROJECT_ID: eng-cache-439121-g2
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/eng-cache-439121-g2/flask-app:latest
  #europe-west10

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:

    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name : Checkout code
              uses: actions/checkout@v3
        
            - name : Set up Python
              uses: actions/setup-python@v4
              with: 
                  python-version: 3.9

                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            
            - name: Train the model (Online Training)
              run: python model.py

            - name: Run Tests
              run: pytest


    deploy:
      name: House price estimator CICD pipeline

env:
  SERVICE_NAME: house price estimator
  PROJECT_ID: eng-cache-439121-g2
  DOCKER_IMAGE_URL: europe-west10-docker.pkg.dev/eng-cache-439121-g2/flask-app:latest
  #europe-west10

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:

    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name : Checkout code
              uses: actions/checkout@v3
        
            - name : Set up Python
              uses: actions/setup-python@v4
              with: 
                  python-version: 3.9

                
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            
            - name: Train the model (Online Training)
              run: python model.py

            - name: Run Tests
              run: pytest

    deploy:

      runs-on: ubuntu-latest
      needs: build-and-test

      steps:
            - name : Checkout code
              uses: actions/checkout@v3

            - name: Athenticate to GCP
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_KEY }}



            - name: Configure GCP project
              run:
                gcloud config set project eng-cache-439121-g2


            - name: Build and Push Docker Image
              run: |
                #docker build -t europe-west10-docker.pkg.dev/eng-cache-439121-g2/flask-app:latest . 
                docker build -t flask-app:latest .
                docker tag flask-app:latest europe-west10-docker.pkg.dev/eng-cache-439121-g2/flask-app/flask-app:latest

                gcloud auth configure-docker  europe-west10-docker.pkg.dev
                docker push europe-west10-docker.pkg.dev/eng-cache-439121-g2/flask-app/flask-app:latest

                gcloud run deploy flask-app \
                 --image europe-west10-docker.pkg.dev/eng-cache-439121-g2/flask-app/flask-app:latest \
                 --platform managed \
                 --region europe-west10 \
                 --allow-unauthenticated
                
